#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'rvm',
  :git => 'https://github.com/fnichol/chef-rvm'

cookbook 'apt',
    git: 'https://github.com/fnichol/chef-apt'

cookbook 'git',
    git: 'https://github.com/fnichol/chef-git.git'

cookbook 'build-essential'

cookbook 'java'
